const foods = {
  쌀국수: { category: "면장님", img: "/img/food-img/" },
  냉면: { category: "면장님", img: "/img/food-img/" },
  우동: { category: "면장님", img: "/img/food-img/" },
  열무국수: { category: "면장님", img: "/img/food-img/" },
  짜장면: { category: "면장님", img: "/img/food-img/" },
  해물칼국수: { category: "면장님", img: "/img/food-img/해물칼국수.jpg" },
  제육볶음: { category: "애국자", img: "/img/food-img/" },
  쭈꾸미볶음: { category: "애국자", img: "/img/food-img/" },
  두부김치: { category: "애국자", img: "/img/food-img/" },
  오리주물럭: { category: "애국자", img: "/img/food-img/" },
  계란말이: { category: "애국자", img: "/img/food-img/" },
  갈치조림: { category: "애국자", img: "/img/food-img/" },
  순대국밥: { category: "국밥부장관", img: "/img/food-img/" },
  뼈다귀해장국: { category: "국밥부장관", img: "/img/food-img/" },
  콩나물국밥: { category: "국밥부장관", img: "/img/food-img/" },
  선지해장국: { category: "국밥부장관", img: "/img/food-img/" },
  내장국밥: { category: "국밥부장관", img: "/img/food-img/" },
  돌솥알밥: { category: "비빔대감", img: "/img/food-img/" },
  육회비빔밥: { category: "비빔대감", img: "/img/food-img/육회비빔밥.jpg" },
  꼬막비빔밥: { category: "비빔대감", img: "/img/food-img/꼬막비빔밥.jpg" },
  강된장비빔밥: { category: "비빔대감", img: "/img/food-img/" },
  전주비빔밥: { category: "비빔대감", img: "/img/food-img/전주비빔밥.jpg" },
  케이준치킨샐러드: {
    category: "샐러디안",
    img: "/img/food-img/케이준치킨샐러드.jpg",
  },
  훈제연어샐러드: { category: "샐러디안", img: "/img/food-img/" },
  리코타치즈샐러드: {
    category: "샐러디안",
    img: "/img/food-img/리코타치즈샐러드.jpg",
  },
  훈제목살샐러드: {
    category: "샐러디안",
    img: "/img/food-img/훈제목살샐러드.jpg",
  },
  쉬림프에그샐러드: {
    category: "샐러디안",
    img: "/img/food-img/쉬림프에그샐러드.jpg",
  },
  햄치즈샌드위치: {
    category: "샌드위치백작",
    img: "/img/food-img/햄치즈샌드위치.jpg",
  },
  에그마요샌드위치: { category: "샌드위치백작", img: "/img/food-img/" },
  클럽샌드위치: {
    category: "샌드위치백작",
    img: "/img/food-img/클럽샌드위치.jpg",
  },
  BLT샌드위치: {
    category: "샌드위치백작",
    img: "/img/food-img/BLT샌드위치.png",
  },
  연어베이글샌드위치: {
    category: "샌드위치백작",
    img: "/img/food-img/연어베이글샌드위치.jpg",
  },
};
